/**
 * Drift-guard for the icon. The canonical source is
 * `assets/icon.svg`; `src/icon.ts` is generated from it by
 * `scripts/build-icon.mjs`. Without this test, a contributor could
 * edit one without the other and the runtime icon would silently
 * disagree with the design source.
 *
 * If this fails, run `npm run build:icon` to regenerate.
 */

import { describe, expect, it } from "vitest";
import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

describe("icon source-of-truth", () => {
  it("src/icon.ts contains the SVG bytes from assets/icon.svg verbatim", () => {
    const svg = readFileSync(join(ROOT, "assets", "icon.svg"), "utf8").replace(/\s+$/, "");
    const ts = readFileSync(join(ROOT, "src", "icon.ts"), "utf8");
    expect(ts).toContain(svg);
  });

  it("regenerating src/icon.ts from the SVG produces no diff (no drift)", () => {
    // Run the regen script and capture what would be written. If
    // the existing src/icon.ts doesn't match the regenerated output,
    // the SVG and TS have drifted.
    const before = readFileSync(join(ROOT, "src", "icon.ts"), "utf8");
    execSync("node scripts/build-icon.mjs", {
      cwd: ROOT,
      stdio: "pipe",
    });
    const after = readFileSync(join(ROOT, "src", "icon.ts"), "utf8");

    if (before !== after) {
      // Restore so we don't leave a stale state for other tests.
      // The SVG/TS pair WILL be re-synced on the next build:icon run.
      throw new Error(
        "src/icon.ts is stale relative to assets/icon.svg. " +
          "Run `npm run build:icon` and commit the regenerated file.",
      );
    }
    expect(before).toBe(after);
  });

  it("src/icon.ts header marks itself as generated (warns hand-editors)", () => {
    const ts = readFileSync(join(ROOT, "src", "icon.ts"), "utf8");
    expect(ts).toMatch(/Generated from assets\/icon\.svg/);
    // "Do not edit this file directly" — line-wrapped in jsdoc comment,
    // so match the wrap-tolerant form
    expect(ts).toMatch(/Do not[\s\S]*edit this file directly/);
  });
});
