#!/usr/bin/env node
/**
 * Regenerate src/icon.ts from assets/icon.svg.
 *
 * The icon ships in two forms at runtime:
 *   - Embedded as a `data:image/svg+xml;base64,...` URI in the MCP
 *     `serverInfo.icons` array (works on every transport, no HTTP
 *     route needed).
 *   - Served at `/icon.svg` and `/favicon.ico` by the HTTP transport,
 *     for clients that prefer to fetch a URL.
 *
 * Both forms come from the same `ICON_SVG` constant in src/icon.ts,
 * which is generated by this script from the canonical `assets/icon.svg`.
 *
 * Run: `npm run build:icon` (also chained from `npm run build`).
 *
 * A drift-guard test (`tests/icon-source.test.ts`) fails CI if
 * `src/icon.ts` falls out of sync with `assets/icon.svg`.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SVG_PATH = join(ROOT, "assets", "icon.svg");
const TS_PATH = join(ROOT, "src", "icon.ts");

const svg = readFileSync(SVG_PATH, "utf8").replace(/\s+$/, "");

// Defensive: backticks and ${ would break the template literal embed.
// Standard SVGs don't contain these, but escape just in case to keep
// the script robust against future SVG edits.
const escapedSvg = svg.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const generated = `/**
 * The capsulemcp icon. Stylised diagonal capsule: two halves with a
 * faint highlight stripe. Designed for crisp display down to 16x16.
 * Visually neutral — does not reproduce any Capsule CRM trademark.
 *
 * Generated from assets/icon.svg by scripts/build-icon.mjs. **Do not
 * edit this file directly** — edit the SVG and re-run \`npm run
 * build:icon\` (or \`npm run build\`, which chains it).
 *
 * This file is generated DATA: the raw SVG plus its \`data:\` URI
 * form. The \`serverInfo.icons\` ARRAY shape (URL form vs data URI
 * form vs both, ordering, sizes hints) is hand-edited orchestration
 * and lives in \`src/icon-builder.ts\` — kept out of this generator
 * so the icon-array shape can evolve without touching the SVG.
 *
 * Exposed two ways at runtime:
 *   - Embedded as a \`data:\` URI in the MCP \`serverInfo.icons\` array
 *     (spec-compliant; works without any HTTP route — stdio path).
 *   - Served at \`/icon.svg\` and \`/favicon.ico\` by the HTTP entry,
 *     so clients that prefer to fetch a URL get a real HTTPS resource
 *     (some UIs' CSP blocks \`data:\` image srcs — URL form survives).
 */

export const ICON_SVG = \`${escapedSvg}\`;

export const ICON_DATA_URI = \`data:image/svg+xml;base64,\${Buffer.from(ICON_SVG, "utf8").toString("base64")}\`;
`;

writeFileSync(TS_PATH, generated, "utf8");
console.log(
  `Regenerated ${TS_PATH.replace(`${ROOT}/`, "")} from ${SVG_PATH.replace(`${ROOT}/`, "")}`,
);
